In [1]:
import nivapy3 as nivapy
import numpy as np
import pandas as pd

In [2]:
eng = nivapy.da.connect()

Username:  ···
Password:  ···············


Connection successful.


# Link old and new ICPW station codes

We need a mapping between the original ICPW stations and the new ones created for the trends work in 2018.

**This notebook is a start, but the code does not work robustly and needs further checking**.

In [3]:
stn_df = pd.read_excel("../data/all_icpw_sites_may_2020.xlsx")
resa_stns = nivapy.da.select_resa_stations(eng)
ids = []
cds = []
for idx, row in stn_df.iterrows():
    code = row["station_code"].replace("Tr18_", "")
    name = row["station_name"]
    sid = row["station_id"]

    df = resa_stns.query("station_code == @code")
    if len(df) == 0:
        df2 = resa_stns.query("station_name == @name")
        if len(df2) == 0:
            ids.append(np.nan)
            cds.append(np.nan)
        elif len(df2) == 1:
            ids.append(df2["station_id"].values[0])
            cds.append(df2["station_code"].values[0])
        else:
            df2 = df2.query("station_id != @sid")
            if len(df2) > 1:
                print(df2["station_id"].unique())
            ids.append(df2["station_id"].values[0])
            cds.append(df2["station_code"].values[0])
    elif len(df) == 1:
        ids.append(df["station_id"].values[0])
        cds.append(df["station_code"].values[0])
    else:
        ids.append(np.nan)
        cds.append(np.nan)

stn_df["old_id"] = ids
stn_df["old_code"] = cds
stn_df.to_csv('test.csv')

19726 stations in the RESA database.
[29444 37372]
[29379 37381]
[  147 15231]
[29308 36757]
[23601 30952 30973 36571 36689]
[29300 30932 36750]
[  196 32003]
[  105   174 38240]
[  170 15992]
[  181 30301]
[  150 10655 18285 20964]
[  172 18972]
[12710 35316]
[  104 29926]
[  168  3314  3352 10181 10334 18011 18167 18933 20808]
[  162 17878 23750]
[29358 31171 36813]
[29294 31175 36743]
[29302 30917 36752]
[30236 30237]
[29348 30981 36797]
[29351 30879 36804]
[29364 30901 36821]
[23604 30897 36800]
[30906 36658]
[29333 30894 36785]
[  129 22652 23322]
[  105   174 38292]
[  101 10292 11727 15297 15353 17904 34584]
[  187 10773 15677 17840]
[  100 10108 17980]
[  103  3351 10625 15242 15735 15993 17957 18047 18253 18420 19601 23406
 29568 35079]
[  185 10553 17994 20683 35084]
[  161 20674]
[  156 15998]
[30992 36458 36561]
[29326 30937 36777]
[29293 30978 36742]
[29342 36793]
[31158 36578]
[31159 36636]
[31160 36690]
[30966 36583]
[36681 36682]
[31162 36670]
[31163 36711]
[31164 36731